export const ROLES = {
    ADMIN: 'ADMIN',
    DOCTOR: 'DOCTOR',
    PARENT: 'PARENT',
    CHILD: 'CHILD'
};

export const PERMISSIONS = {
    VIEW_ASSIGNED_CHILDREN: 'viewAssignedChildren',
    REVIEW_NUTRIENT_HISTORY: 'reviewNutrientHistory',
    ADD_MANUAL_RECOMMENDATION: 'addManualRecommendation',
    VIEW_DEFICIENCY_ALERTS: 'viewDeficiencyAlerts',
    DOWNLOAD_HEALTH_REPORT: 'downloadHealthReport',
    MANAGE_CHILD_PROFILE: 'manageChildProfile',
    ENTER_DAILY_FOOD_INTAKE: 'enterDailyFoodIntake',
    VIEW_RECOMMENDATIONS: 'viewRecommendations',
    VIEW_BMI_TRENDS: 'viewBMITrends',
    VIEW_CHILD_DASHBOARD: 'viewChildDashboard',
    MANAGE_USERS: 'manageUsers',
};

export const ROLE_PERMISSIONS = {
    [ROLES.DOCTOR]: [
        PERMISSIONS.VIEW_ASSIGNED_CHILDREN,
        PERMISSIONS.REVIEW_NUTRIENT_HISTORY,
        PERMISSIONS.ADD_MANUAL_RECOMMENDATION,
        PERMISSIONS.VIEW_DEFICIENCY_ALERTS,
        PERMISSIONS.DOWNLOAD_HEALTH_REPORT,
    ],
    [ROLES.PARENT]: [
        PERMISSIONS.MANAGE_CHILD_PROFILE,
        PERMISSIONS.ENTER_DAILY_FOOD_INTAKE,
        PERMISSIONS.VIEW_RECOMMENDATIONS,
        PERMISSIONS.VIEW_DEFICIENCY_ALERTS,
        PERMISSIONS.VIEW_BMI_TRENDS,
    ],
    [ROLES.CHILD]: [
        PERMISSIONS.VIEW_CHILD_DASHBOARD
    ],
    [ROLES.ADMIN]: Object.values(PERMISSIONS)
};
